"""Generate docs/SPECS.md, a resume-ready spec sheet, from saved benchmark data.

    uv run task specs

Rule (owner decision 2026-10-09): every number must trace to docs/BENCHMARKS.md (that is,
docs/benchmarks/*.json written by ``bench`` / ``vlm-bakeoff``) or to the repository's CI
configuration. Nothing is estimated here: this script only reads and formats. The Nebius
runner is described as implemented and contract-tested, with no cloud timings.
"""

from __future__ import annotations

import json
import re
import statistics
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
BENCH = ROOT / "docs" / "benchmarks" / "bench.json"
VLM = ROOT / "docs" / "benchmarks" / "vlm_bakeoff.json"
OUT = ROOT / "docs" / "SPECS.md"
REQUIRED_CHECKS = [
    "python (format, lint, types, tests)",
    "openapi drift",
    "kotlin client (build + test)",
    "backend image",
    "blender-gate",
]


def ci_jobs() -> list[tuple[str, str]]:
    """(workflow, job name) pairs from .github/workflows/*.yml (plain text parsing)."""
    out = []
    for wf in sorted((ROOT / ".github" / "workflows").glob("*.yml")):
        text = wf.read_text(encoding="utf-8")
        jobs = text.split("\njobs:\n", 1)[-1]
        for m in re.finditer(
            r"^  ([a-z0-9_-]+):\n(?:    .*\n)*?    name: (.+)$|^  ([a-z0-9_-]+):$", jobs, re.M
        ):
            key = m.group(1) or m.group(3)
            name = (m.group(2) or key).strip()
            out.append((wf.stem, name))
    return list(dict.fromkeys(out))


def ruleset_active() -> bool:
    """True when GitHub reports an active ruleset on this repository (via the gh CLI)."""
    import subprocess

    try:
        out = subprocess.run(
            [  # noqa: S607
                "gh",
                "api",
                "repos/{owner}/{repo}/rulesets",
                "--jq",
                '[.[] | select(.enforcement == "active")] | length',
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return out.returncode == 0 and out.stdout.strip() not in ("", "0")


def build(bench: dict[str, Any], vlm: dict[str, Any] | None) -> str:
    rows = bench["scenes"]
    q = [r for r in rows if r["runner"] == bench["quality_runner"]]
    n = len(q)
    before = statistics.median(r["slip_cm"]["original"] for r in q)
    after_a = statistics.median(r["slip_cm"]["A"] for r in q)
    after_b = statistics.median(r["slip_cm"]["B"] for r in q)
    accepted = sum(1 for r in q if r["accepted"]["A"] or r["accepted"]["B"])
    collateral = max(v for r in q for v in r["collateral_max_cm"].values() if v is not None)
    per_runner = {
        runner: statistics.median(r["upload_to_review_s"] for r in rows if r["runner"] == runner)
        for runner in dict.fromkeys(r["runner"] for r in rows)
    }
    priced = [r["model_cost_usd"] for r in rows if r["model_cost_usd"] is not None]
    cost = statistics.median(priced) if priced else None
    startup = (bench.get("startup") or {}).get("overhead_per_step_s")
    tests = bench["tests"]
    offline = sum(
        v
        for k, v in tests.items()
        if k in ("unit", "contract", "fault", "golden", "integration (offline)")
    )
    env = bench["environment"]
    winner = (vlm or {}).get("winner") or {}
    src = "([BENCHMARKS.md](BENCHMARKS.md))"

    lines = [
        "# Kinesis: spec sheet",
        "",
        f"Generated by `uv run task specs` from `docs/benchmarks/*.json` (bench run {bench['finished']}, commit "
        f"`{env['commit']}`; {env['os']}, {env['cpu_count']} logical CPUs, GPU {env['gpu'] or 'none'}). "
        "Every number below traces to [BENCHMARKS.md](BENCHMARKS.md) or to the repository's CI configuration.",
        "",
        "## Headline numbers",
        "",
        f"- **Median planted foot slip across {n} scenes:** {before:.2f} cm before; {after_a:.2f} cm after candidate A and "
        f"{after_b:.2f} cm after candidate B. {accepted}/{n} scenes had at least one candidate under 1 cm {src}.",
        f"- **Zero collateral motion:** the largest change to any bone outside the repaired leg was {collateral:.4f} cm across all scenes {src}.",
    ]
    for runner, secs in per_runner.items():
        label = {
            "local": "host Blender",
            "container4": "the worker container on 4 CPUs",
            "container2": "the worker container on 2 CPUs",
        }.get(runner, runner)
        runner_rows = [r for r in rows if r["runner"] == runner]
        model_s = statistics.median(
            (r["stage_s"].get("plan_repair") or 0) + (r["stage_s"].get("evaluate") or 0)
            for r in runner_rows
        )
        if any(r["model_cost_usd"] is not None for r in runner_rows):
            detail = f", including a median {model_s:.1f} s of Token Factory calls (plan + visual review)"
        else:
            detail = ", without model calls (deterministic presets)"
        lines.append(
            f"- **Upload → A/B ready for review:** median {secs:.1f} s with {label}{detail} {src}."
        )
    if cost is not None:
        lines.append(
            f"- **Model cost per job:** median ${cost:.4f} for the Nemotron 3 Super plan plus visual review, through Nebius Token Factory {src}."
        )
    if startup is not None:
        lines.append(f"- **Container start-up overhead:** {startup:.2f} s per worker step {src}.")
    if winner:
        lines.append(
            f"- **Vision model chosen by bake-off:** `{winner['model']}`, with no wrong answer in {winner['trials']} "
            f"trials that have a known answer (a small sample), {winner['valid_json_rate']:.0%} valid JSON and "
            f"${winner['cost_per_review_usd']:.4f} per review {src}."
        )
    lines += [
        "",
        "## Architecture",
        "",
        "- **Repair worker.** A Blender 4.5 worker runs headless in Docker (Ubuntu 24.04, with Mesa for software rendering). "
        "It extracts the motion, applies each candidate as a separate NLA layer without touching the original action, and "
        "renders A/B previews.",
        "- **Job engine.** A DAG engine runs candidates A and B concurrently, with retries, a circuit breaker and result "
        "caches, behind FastAPI with SQLite (and an optional Redis cache).",
        "- **Repair math.** A numpy core does contact detection and two-bone IK repair.",
        "- **Models.** An NVIDIA Nemotron 3 Super planner, via Nebius Token Factory, chooses the A/B parameters within "
        "validated bounds. A benchmarked vision model reviews the rendered frames.",
        "- **Review client.** A Compose Desktop client, generated from the OpenAPI contract, shows Original, A and B in "
        "sync, and the animator decides.",
        "- **Cloud runner.** The Nebius Serverless Jobs runner is implemented and contract-tested against the Nebius "
        "Serverless Jobs API; live runs are pending.",
        "",
        "## Engineering quality",
        "",
        f"- **Tests:** {offline} offline tests ("
        + ", ".join(
            f"{k} {v}"
            for k, v in tests.items()
            if k in ("unit", "contract", "fault", "golden", "integration (offline)")
        )
        + "), "
        f"plus {tests.get('blender', 0)} headless-Blender tests, {tests.get('container', 0)} container parity test(s), "
        f"{tests.get('kotlin client', 0)} Kotlin client tests and {tests.get('live (gated)', 0)} gated live tests {src}.",
        "- **Golden parity:** the containerized worker reproduces the golden metrics of host Blender. A nightly CI job checks this, and opens an issue on failure.",
        "- **Fault injection:** every row of the failure-mode matrix has a scenario, covering model timeouts and 429s, the breaker, Blender crashes and timeouts, malformed results, Redis outage, cancellation, and Nebius job errors.",
        "- **CI jobs:** " + "; ".join(f"`{wf}` / {name}" for wf, name in ci_jobs()) + ".",
        (
            "- **Required checks on `main`** (squash-only PRs, enforced by a GitHub ruleset): "
            if ruleset_active()
            else "- **Required checks on `main`** (proposed in `infra/github/ruleset-main.json`; not yet enforced): "
        )
        + ", ".join(f"`{c}`" for c in REQUIRED_CHECKS)
        + ".",
        "",
        "## Suggested resume bullets",
        "",
        f"- Built Kinesis, an AI-assisted animation repair tool. It cut median planted foot slip from {before:.1f} cm to "
        f"{min(after_a, after_b):.2f} cm across {n} benchmark scenes with zero collateral motion, using non-destructive "
        "Blender NLA layers.",
        f"- Designed a DAG job engine (FastAPI, asyncio, SQLite) that runs repair candidates concurrently in headless "
        f"Blender, with retries, a circuit breaker and caching. Upload to A/B review takes a median "
        f"{per_runner.get('container4', per_runner.get('local', 0)):.1f} s on 4 CPUs without model calls.",
        "- Integrated NVIDIA Nemotron 3 Super through Nebius Token Factory as a bounded planner behind a validation gate"
        + (f", at a median model cost of ${cost:.4f} per repair" if cost is not None else "")
        + ". Chose the vision model by an evidence-based bake-off.",
        "- Containerized the Blender worker and proved golden-result parity with host Blender in CI. Implemented and "
        "contract-tested a Nebius Serverless Jobs runner with a budget guard and a watchdog.",
        "- Shipped a Kotlin Compose Desktop review client generated from the OpenAPI contract, with synchronized "
        "Original/A/B playback, backed by "
        f"{offline + tests.get('kotlin client', 0)} automated tests and fault-injection scenarios.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    if not BENCH.exists():
        print("docs/benchmarks/bench.json is missing: run `uv run task bench` first")
        return 1
    bench = json.loads(BENCH.read_text(encoding="utf-8"))
    vlm = json.loads(VLM.read_text(encoding="utf-8")) if VLM.exists() else None
    OUT.write_text(build(bench, vlm), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
